# Generated by Django 4.2.1 on 2023-05-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversatioions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='connent',
            new_name='content',
        ),
    ]
